# general settings
name: train_UNetx4bicubic
model_type: CLIPUNetModel
scale: 2
num_gpu: auto  # auto: can infer from your visible devices automatically. official: 4 GPUs
manual_seed: 0

# ----------------- options for synthesizing training data in RealESRNetModel ----------------- #
high_order_degradation: False
gt_size: 224

# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: /mnt/slurm_home/xychen/DF2K/DF2K_train_HR_sub_bicubic
    dataroot_lq: /mnt/slurm_home/xychen/DF2K/DF2K_train_HR_sub_bicubicLQ
    io_backend:
      type: disk

    gt_size: 224
    use_hflip: True
    use_rot: False

    # data loader
    num_worker_per_gpu: 5
    batch_size_per_gpu: 24
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  # Uncomment these for validation
  val:
    name: validation
    type: PairedImageDataset
    dataroot_gt: /mnt/slurm_home/xychen/DF2K/val_gt
    dataroot_lq: /mnt/slurm_home/xychen/DF2K/val_lq2
    io_backend:
      type: disk
  #  div2k 100 val

# network structures
network_g:
  type: UNetGenerator
  # clip_path: /Users/x/Desktop/BasicSR/experiments/pretrained_models/CLIP/RN50.pth
  num_out_ch: 3
  scale: 2
  pretrained: true
  # num_clip_features: 4
  # finetune: False

# path
path:
  pretrain_network_g: ~
  experiments_root: /mnt/slurm_home/xychen/experiments
  # param_key_g: params_ema
  # strict_load_g: False
  # resume_state: experiments/790000.state

# training settings
train:
  # ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [1000000]
    gamma: 0.5

  total_iter: 1000000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# Uncomment these for validation
# validation settings
val:
  val_freq: !!float 1e3
  save_img: True

  metrics:
    psnr: # metric name
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false

    percep_loss:
      type: calculate_percep_loss
      better: lower


# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

